; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nanoatmega328new]
platform = atmelavr
board = nanoatmega328new
framework = arduino
lib_deps =
	marcoschwartz/LiquidCrystal_I2C
	paulstoffregen/Encoder
monitor_speed = 115200
upload_speed = 115200

build_flags =
    -Wall          ; "Warning All": Aktiviert die gängigsten Warnungen, die die meisten C++-Fehler abdecken.
    -Wextra        ; Aktiviert zusätzliche Warnungen, die bei Standard-Einstellungen (Wall) ignoriert werden (z.B. ungenutzte Parameter).
    -Wconversion   ; Sehr wichtig: Warnt vor Typumwandlungen, bei denen Daten verloren gehen könnten oder sich das Vorzeichen ändert (signed <-> unsigned).
    ;-Werror        ; (Optional) Behandelt jede Warnung wie einen Fehler und bricht den Build ab – für maximal disziplinierten Code.